site_name: SFe - Bringing music to new heights
site_description: Official specification for the SF-enhanced format.
site_author: SFe Team
site_url: https://sfe-team-was-taken.github.io/SFe/
copyright: Copyright © 2025 SFe Team and contributors.
  The SFe Team is in no way sponsored by or otherwise affiliated with Creative Technology Ltd. or E-mu Systems, Inc. SoundFont® is a registered trademark of Creative Technology Ltd.
repo_url: https://github.com/SFe-Team-was-taken/SFe
repo_name: SFe-Team-was-taken/SFe

docs_dir: ./
site_dir: ./gh-pages
use_directory_urls: false

plugins:
  - search
  - same-dir
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      cache_safe: true


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - smarty
  - toc
  - tables
  - meta

theme:
  name: material
  logo: assets/images/favicon.png
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - content.code.copy
    - content.code.select
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - navigation.expand

    - toc.follow

    - header.autohide

extra_css:
  - stylesheets/extra.css

nav:
  - README.md
  - Issue Tracker: 'https://github.com/SFe-Team-was-taken/SFe/issues'
  - Specification:
      - specification/index.md
      - specification/section-1.md
      - specification/section-2.md
      - specification/section-3.md
      - specification/section-4.md
      - specification/section-5.md
      - specification/section-6.md
      - specification/section-7.md
      - specification/section-8.md
      - specification/section-9.md
      - specification/section-10.md
      - specification/section-11.md
      - specification/section-12.md
  - Legacy SF2.04 Specification: https://raw.githubusercontent.com/davy7125/soundfont-standard-v3/117539e5dc2d35d7a6273ba7bc319e7d1e1c9a67/sfspec24.pdf
  - contributing.md
  - SECURITY.md
  - code-of-conduct.md
  - License: LICENSE.md
  - Revision History: draft-revision-history.md
